### ISSUE TITLE
Error importing

### ISSUE THREAD

**Issue by trapagual** [Reinsys/intel-xdk-ionic-angularjs-starter-template#1]
Hi
Downloaded project as zip.
In XDK, "Import your HTML5 code base". 
Indicated the folder IonicProjectStarter

XDK says:Error creating project: Import directory contains Intel XDK files

What am I doing wrong?

**Comment by adefokun** [comment]
Open the unzipped folder
Open intel-xdk-ionic-angularjs-starter-template-masterfolder
Copy IonicProjectStarter folder to your projects directory and rename to
"YourProjectName"
Open "YourProjectName" and rename "IonicProjectStarter.xdk" to
"YourProjectName.xdk"
Open your IntelXDK software
Under Projects tab of IntelXDK, click OPEN AN INTEL XDK PROJECT
Browse to "YourProjectName" folder in your projects directory
Click and open "YourProjectName.xdk"

That will be it. You will be prompted that it was created by an older
version of intelXDK, so click "Upgrade" to continue. That may take a few
seconds to a minute.
